### PR TITLE
switch library

### PR DESCRIPTION
**Pull request by c2bo**
- switches to https://github.com/openwallet-foundation-labs/sd-jwt-js
- adds highlight to disclosures in addition to digests
- supports recursive disclosures now

still has some problem with the signature validation - trying to figure that one out

### CODE REVIEW

**Comment by c2bo** [comment]
No idea what the issue with signature validation is atm :/ Everything else seems to be working now

**Comment by cre8** [comment]
> No idea what the issue with signature validation is atm :/ Everything else seems to be working now

Have you a valid sd-jwt with the public key? I see only this error in the console ` Failed to execute 'importKey' on 'SubtleCrypto': Algorithm: Unrecognized name`

**Comment by cre8** [comment]
image

Your referenced curve in https://github.com/schlagtim/sd-jwt-tool/blob/main/src/routes/%2Bpage.svelte#L17 is not supported by the browsers, just by nodejs. Using the `P-256` curve will work in all browsers and also nodejs.

**Comment by c2bo** [comment]
> image
> 
> Your referenced curve in https://github.com/schlagtim/sd-jwt-tool/blob/main/src/routes/%2Bpage.svelte#L17 is not supported by the browsers, just by nodejs. Using the `P-256` curve will work in all browsers and also nodejs.

I am defaulting to P-256 in this PR (and also changed the example to it). When debugging, I see that the public key seems to be be imported properly and the verify function gets called but verification fails.
I am not very used to typescript, so it's probably just a stupid problem on my side converting between the different data formats (base64, uint8array etc).

**Comment by cre8** [comment]
My bad, I just checked the default branch and saw the error. I can spend some time on this tomorrow.

**Comment by cre8** [comment]
Opened a PR #3 since I was not able to push to the PR

**Pull request merged**
